export default {
  LOGIN: 'Giriş Sayfası',
  HOME: 'Gelen Mesajlar',
  GROUPS: 'Ders Sohbetleri',
  UNICS: 'özel Mesajlar',
  TOPNAVIGATOR: 'Fırat İletisim Platformu',
  DRAWERNAVIGATOR: 'DrawerBar',
  COMMON: 'Genel Duyurular',
  SECTION: 'Bölüm Duyuruları',
  EXIT: 'Çıkış',
  MESSAGE: 'Mesajlar',
  ALL: 'Gelen Mesajlar',
  ACADEMIC_LIST: 'Akademisyen Listesi',
  GROUP_PROFILE: 'Grup Profili',
  USER_PROFILE: 'Kullanıcı Profilleri',
  SECTION_DETAIL: 'Bölüm Duyuruları Detay',
  COMMON_DETAIL: 'Genel Duyurular Detay',
};
